// flow-typed signature: 85a49e882d7b0306e40c93e06990c41a
// flow-typed version: <<STUB>>/babel-plugin-istanbul_v^3.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-istanbul/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-istanbul/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib/index'>;
}
