// flow-typed signature: 56f7dbb12e1349d388a021f8da2db04e
// flow-typed version: <<STUB>>/lodash.size_v^4.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.size/index' {
  declare module.exports: $Exports<'lodash.size'>;
}
declare module 'lodash.size/index.js' {
  declare module.exports: $Exports<'lodash.size'>;
}
